### ISSUE TITLE
Fade Out CoverPop-cover on close?

### ISSUE THREAD

**Issue by spring-91** [tylerpearson/CoverPop#18]
Hi there,

Managed to get the pop-up to fade in on load but can't seem to get it to fade-out on close. Could you point me in the right direction on how I would achieve this?

Many thanks!

**Comment by austinsamsel** [comment]
you can do it by making a new close link with a the class ".js-closeCoverPop" then calling a click handler on it. You then call the CoverPop to close once the fadeout is complete.
```
  $( ".js-closeCoverPop" ).click(function() {
    $('#CoverPop-cover').fadeOut(250, 'swing', function(){
      CoverPop.close();
    });
  });
```
